import numpy as np
import matplotlib.pyplot as plt

ours = np.load('plot_data/backup/ours.npz')
v10 = np.load('plot_data/backup/v10.npz')
v15 = np.load('plot_data/v15.npz')
v20 = np.load('plot_data/backup/v20.npz')

ours_time = ours.get('timestamp')
v10_time = v10.get('timestamp')
v15_time = v15.get('timestamp')
v20_time = v20.get('timestamp')

fig = plt.figure(figsize=(15, 12))

plt.subplot(7, 1, 1)
plt.plot(ours_time, ours.get('y0_true'), 'r', label='Ours')
plt.plot(v10_time, v10.get('y0_true'), 'g--', label = '$L=4$m, $v_{ref}=10$m/s')
plt.plot(v15_time[:-28], v15.get('y0_true')[:-28], 'b--', label = '$L=6$m, $v_{ref}=15$m/s')
plt.plot(v20_time, v20.get('y0_true'), 'y--', label = '$L=8$m, $v_{ref}=20$m/s')
plt.xlim(0, 72)
plt.ylim(-1.75, 1.75)
plt.ylabel('$y_0$\n[m]')
plt.legend(loc=1)
plt.grid(True)

plt.subplot(7, 1, 2)
plt.plot(ours_time, ours.get('eps0_true'), 'r', label='Ours')
plt.plot(v10_time, v10.get('eps0_true'), 'g--', label = '$L=4$m, $v_{ref}=10$m/s')
plt.plot(v15_time[:-28], v15.get('eps0_true')[:-28], 'b--', label = '$L=6$m, $v_{ref}=15$m/s')
plt.plot(v20_time, v20.get('eps0_true'), 'y--', label = '$L=8$m, $v_{ref}=20$m/s')
plt.ylabel('$\epsilon_0$\n[rad]')
plt.xlim(0, 72)
plt.ylim(-0.2, 0.2)
plt.legend(loc=1)
plt.grid(True)

plt.subplot(7, 1, 3)
plt.plot(ours_time, ours.get('avg_unc_y4'), 'k', label='$L=4$m')
plt.plot(ours_time, ours.get('avg_unc_y6'), 'r', label='$L=6$m')
plt.plot(ours_time, ours.get('avg_unc_y8'), 'c', label='$L=8$m')
plt.plot(ours_time, ours.get('avg_unc_y10'), 'm', label='$L=10$m')
plt.xlim(0, 72)
plt.legend(loc=1)
plt.ylabel('Averaged\n$y_L$ uncertainty\n[m]')
plt.grid(True)

plt.subplot(7, 1, 4)
plt.plot(ours_time, ours.get('avg_unc_eps4'), 'k', label='$L=4$m')
plt.plot(ours_time, ours.get('avg_unc_eps6'), 'r', label='$L=6$m')
plt.plot(ours_time, ours.get('avg_unc_eps8'), 'c', label='$L=8$m')
plt.plot(ours_time, ours.get('avg_unc_eps10'), 'm', label='$L=10$m')
plt.xlim(0, 72)
plt.legend(loc=1)
plt.ylabel('Averaged\n$\epsilon_L$ uncertainty\n[rad]')
plt.grid(True)

plt.subplot(7, 1, 5)
plt.plot(ours_time, ours.get('lookahead'), 'r', label='Ours')
plt.plot(v10_time, v10.get('lookahead'), 'g--', label='$L=4$m, $v_{ref}=10$m/s')
plt.plot(v15_time[:-28], v15.get('lookahead')[:-28], 'b--', label='$L=6$m, $v_{ref}=15$m/s')
plt.plot(v20_time, v20.get('lookahead'), 'y--', label='$L=8$m, $v_{ref}=20$m/s')
plt.xlim(0, 72)
plt.legend(loc=1)
plt.ylabel('$L$\n[m]')
plt.grid(True)

plt.subplot(7, 1, 6)
plt.plot(ours_time, ours.get('speed'), 'r', label='Ours')
plt.plot(v10_time, v10.get('speed'), 'g--', label='$L=4$m, $v_{ref}=10$m/s')
plt.plot(v15_time[:-28], v15.get('speed')[:-28], 'b--', label='$L=6$m, $v_{ref}=15$m/s')
plt.plot(v20_time, v20.get('speed'), 'y--', label='$L=8$m, $v_{ref}=20$m/s')
plt.xlim(0, 72)
plt.legend(loc=1)
plt.ylabel('$v_x$\n[m/s]')
plt.grid(True)

plt.subplot(7, 1, 7)
plt.plot(ours_time, ours.get('distance'), 'r', label='Ours')
plt.plot(v10_time, v10.get('distance'), 'g--', label='$L=4$m, $v_{ref}=10$m/s')
plt.plot(v15_time[:-28], v15.get('distance')[:-28], 'b--', label='$L=6$m, $v_{ref}=15$m/s')
plt.plot(v20_time, v20.get('distance'), 'y--', label='$L=8$m, $v_{ref}=20$m/s')
plt.xlim(0, 72)
plt.legend(loc=1)
plt.xlabel('Time [s]')
plt.ylabel('Traveled\ndistance\n[m]')
plt.grid(True)

plt.show()